#macro FONT_CHARS "abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ1234567890.,!?'-+/:"
#macro RIGHT 0
#macro UP 1
#macro LEFT 2
#macro DOWN 3
#macro TREE_TILES 1000
#macro IDLE 0
#macro APPROACH 1
#macro ATTACK 2
#macro RETURN 3
#macro HIT 4
#macro RANGED 5
#macro BATTLE_SPACE 480
#macro ACTIVATE 0
#macro FORMAT_TEXT 0
#macro IDLE_SAD 10
#macro APPROACH_SAD 11
#macro ATTACK_SAD 12
#macro RETURN_SAD 13
#macro HIT_SAD 14
#macro RANGED_SAD 15
#macro IDLE_ANGRY 20
#macro APPROACH_ANGRY 21
#macro ATTACK_ANGRY 22
#macro RETURN_ANGRY 23
#macro HIT_ANGRY 24
#macro RANGED_ANGRY 25